import type { Country } from "./types";

export const allCountries: Country[] = [
  { name: "Afghanistan", code: "AFN", flag: "🇦🇫", flagCode: "af" },
  { name: "Albania", code: "ALL", flag: "🇦🇱", flagCode: "al" },
  { name: "Algeria", code: "DZD", flag: "🇩🇿", flagCode: "dz" },
  { name: "Argentina", code: "ARS", flag: "🇦🇷", flagCode: "ar" },
  { name: "Australia", code: "AUD", flag: "🇦🇺", flagCode: "au" },
  { name: "Bahrain", code: "BHD", flag: "🇧🇭", flagCode: "bh" },
  { name: "Bangladesh", code: "BDT", flag: "🇧🇩", flagCode: "bd" },
  { name: "Bolivia", code: "BOB", flag: "🇧🇴", flagCode: "bo" },
  { name: "Brazil", code: "BRL", flag: "🇧🇷", flagCode: "br" },
  { name: "Bulgaria", code: "BGN", flag: "🇧🇬", flagCode: "bg" },
  { name: "Cambodia", code: "KHR", flag: "🇰🇭", flagCode: "kh" },
  { name: "Canada", code: "CAD", flag: "🇨🇦", flagCode: "ca" },
  { name: "Chile", code: "CLP", flag: "🇨🇱", flagCode: "cl" },
  { name: "China", code: "CNY", flag: "🇨🇳", flagCode: "cn" },
  { name: "Colombia", code: "COP", flag: "🇨🇴", flagCode: "co" },
  { name: "Costa Rica", code: "CRC", flag: "🇨🇷", flagCode: "cr" },
  { name: "Croatia", code: "HRK", flag: "🇭🇷", flagCode: "hr" },
  { name: "Czech Republic", code: "CZK", flag: "🇨🇿", flagCode: "cz" },
  { name: "Denmark", code: "DKK", flag: "🇩🇰", flagCode: "dk" },
  { name: "Dominican Republic", code: "DOP", flag: "🇩🇴", flagCode: "do" },
  { name: "Egypt", code: "EGP", flag: "🇪🇬", flagCode: "eg" },
  { name: "Euro Zone", code: "EUR", flag: "🇪🇺", flagCode: "eu" },
  { name: "Fiji", code: "FJD", flag: "🇫🇯", flagCode: "fj" },
  { name: "Ghana", code: "GHS", flag: "🇬🇭", flagCode: "gh" },
  { name: "Guatemala", code: "GTQ", flag: "🇬🇹", flagCode: "gt" },
  { name: "Honduras", code: "HNL", flag: "🇭🇳", flagCode: "hn" },
  { name: "Hong Kong", code: "HKD", flag: "🇭🇰", flagCode: "hk" },
  { name: "Hungary", code: "HUF", flag: "🇭🇺", flagCode: "hu" },
  { name: "Iceland", code: "ISK", flag: "🇮🇸", flagCode: "is" },
  { name: "India", code: "INR", flag: "🇮🇳", flagCode: "in" },
  { name: "Indonesia", code: "IDR", flag: "🇮🇩", flagCode: "id" },
  { name: "Iran", code: "IRR", flag: "🇮🇷", flagCode: "ir" },
  { name: "Israel", code: "ILS", flag: "🇮🇱", flagCode: "il" },
  { name: "Japan", code: "JPY", flag: "🇯🇵", flagCode: "jp" },
  { name: "Jordan", code: "JOD", flag: "🇯🇴", flagCode: "jo" },
  { name: "Kazakhstan", code: "KZT", flag: "🇰🇿", flagCode: "kz" },
  { name: "Kenya", code: "KES", flag: "🇰🇪", flagCode: "ke" },
  { name: "Kuwait", code: "KWD", flag: "🇰🇼", flagCode: "kw" },
  { name: "Laos", code: "LAK", flag: "🇱🇦", flagCode: "la" },
  { name: "Lebanon", code: "LBP", flag: "🇱🇧", flagCode: "lb" },
  { name: "Malaysia", code: "MYR", flag: "🇲🇾", flagCode: "my" },
  { name: "Mexico", code: "MXN", flag: "🇲🇽", flagCode: "mx" },
  { name: "Morocco", code: "MAD", flag: "🇲🇦", flagCode: "ma" },
  { name: "Nepal", code: "NPR", flag: "🇳🇵", flagCode: "np" },
  { name: "New Zealand", code: "NZD", flag: "🇳🇿", flagCode: "nz" },
  { name: "Nigeria", code: "NGN", flag: "🇳🇬", flagCode: "ng" },
  { name: "Norway", code: "NOK", flag: "🇳🇴", flagCode: "no" },
  { name: "Oman", code: "OMR", flag: "🇴🇲", flagCode: "om" },
  { name: "Pakistan", code: "PKR", flag: "🇵🇰", flagCode: "pk" },
  { name: "Paraguay", code: "PYG", flag: "🇵🇾", flagCode: "py" },
  { name: "Peru", code: "PEN", flag: "🇵🇪", flagCode: "pe" },
  { name: "Philippines", code: "PHP", flag: "🇵🇭", flagCode: "ph" },
  { name: "Poland", code: "PLN", flag: "🇵🇱", flagCode: "pl" },
  { name: "Qatar", code: "QAR", flag: "🇶🇦", flagCode: "qa" },
  { name: "Romania", code: "RON", flag: "🇷🇴", flagCode: "ro" },
  { name: "Russia", code: "RUB", flag: "🇷🇺", flagCode: "ru" },
  { name: "Saudi Arabia", code: "SAR", flag: "🇸🇦", flagCode: "sa" },
  { name: "Serbia", code: "RSD", flag: "🇷🇸", flagCode: "rs" },
  { name: "Singapore", code: "SGD", flag: "🇸🇬", flagCode: "sg" },
  { name: "South Africa", code: "ZAR", flag: "🇿🇦", flagCode: "za" },
  { name: "South Korea", code: "KRW", flag: "🇰🇷", flagCode: "kr" },
  { name: "Sri Lanka", code: "LKR", flag: "🇱🇰", flagCode: "lk" },
  { name: "Sweden", code: "SEK", flag: "🇸🇪", flagCode: "se" },
  { name: "Switzerland", code: "CHF", flag: "🇨🇭", flagCode: "ch" },
  { name: "Taiwan", code: "TWD", flag: "🇹🇼", flagCode: "tw" },
  { name: "Tanzania", code: "TZS", flag: "🇹🇿", flagCode: "tz" },
  { name: "Thailand", code: "THB", flag: "🇹🇭", flagCode: "th" },
  { name: "Turkey", code: "TRY", flag: "🇹🇷", flagCode: "tr" },
  { name: "Uganda", code: "UGX", flag: "🇺🇬", flagCode: "ug" },
  { name: "Ukraine", code: "UAH", flag: "🇺🇦", flagCode: "ua" },
  { name: "United Arab Emirates", code: "AED", flag: "🇦🇪", flagCode: "ae" },
  { name: "United Kingdom", code: "GBP", flag: "🇬🇧", flagCode: "gb" },
  { name: "United States", code: "USD", flag: "🇺🇸", flagCode: "us" },
  { name: "Uruguay", code: "UYU", flag: "🇺🇾", flagCode: "uy" },
  { name: "Vietnam", code: "VND", flag: "🇻🇳", flagCode: "vn" },
  { name: "Zambia", code: "ZMW", flag: "🇿🇲", flagCode: "zm" },
];
